name: Quanah Zimmerman
favicon: null
layout_spectrum: 0.50973
typography_spectrum: 0.17506
title: "Quanah Zimmerman's blog"
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f7fcff'
    - '#191919'
    - '#b0c9de'
    - '#638aac'
    - '#3f4a52'
  brandStrength: 1
  lightness: 0.75
  saturation: 0.5
  rhythmicContrast: 0.75
purpose: []
